route:
  group_by: [ alertname ]
  receiver: 'sns' # default receiver
  repeat_interval: 2m


receivers:
  - name: sns
    sns_configs:
      - topic_arn: arn:aws:sns:us-east-1:101981577606:alertmanager-sns-topic
        subject: |-
            High CPU Usage 
        message: |-
            High CPU Usage in the target machine.Please look into it.
        sigv4:
          region: us-east-1
