route:
  group_by: [ alertname ]
  receiver: 'sns' # default receiver
  repeat_interval: 5m


receivers:
  - name: sns
    sns_configs:
      - topic_arn: arn:aws:sns:us-east-1:101981577606:alertmanager-sns-topic
        subject: |-
          #subject
        message: |-
          Hi, Team cpu usage is high,please look at the system.
        sigv4:
          region: us-east-1
